# Generated by Django 6.0.5 on 2026-08-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.CharField(help_text='Numer identyfikacyjny karty / chipa pracownika używany do logowania.', max_length=20, unique=True, verbose_name='Numer chip')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nazwa wyświetlana')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Członek zespołu R&D')], default='member', max_length=10, verbose_name='Rola')),
                ('is_active_chip', models.BooleanField(default=True, verbose_name='Chip aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil (chip)',
                'verbose_name_plural': 'Profile (chip)',
            },
        ),
    ]
