# Generated by Django 6.0.5 on 2026-08-05 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sesja', 'Sesja'), ('archiwum', 'Archiwum')], default='sesja', max_length=10)),
                ('legacy_nr', models.PositiveIntegerField(blank=True, help_text='Nr z pierwotnego archiwum, jeśli dotyczy.', null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa produktu')),
                ('brand', models.CharField(blank=True, default='', max_length=200, verbose_name='Marka')),
                ('category', models.CharField(choices=[('Batony', 'Batony'), ('Granola', 'Granola'), ('Musli', 'Musli'), ('Owsianki', 'Owsianki'), ('Płatki śniadaniowe', 'Płatki śniadaniowe'), ('Ekstrudaty', 'Ekstrudaty'), ('Poduszki', 'Poduszki'), ('Przekąski słodkie', 'Przekąski słodkie'), ('Przekąski wytrawne', 'Przekąski wytrawne'), ('Czekolada', 'Czekolada'), ('Wyroby cukiernicze', 'Wyroby cukiernicze'), ('Napój', 'Napój'), ('Inne', 'Inne')], default='Batony', max_length=100, verbose_name='Kategoria')),
                ('composition', models.TextField(blank=True, default='', verbose_name='Skład')),
                ('allergens', models.TextField(blank=True, default='', verbose_name='Alergeny')),
                ('claims', models.TextField(blank=True, default='', verbose_name='Deklaracje na opakowaniu')),
                ('whats_new', models.TextField(blank=True, default='', verbose_name='Co jest nowe lub ciekawe')),
                ('appearance', models.TextField(blank=True, default='', verbose_name='Wygląd produktu i obserwacje wizualne')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Wniosek z degustacji / insight')),
                ('energia_kcal', models.CharField(blank=True, default='', max_length=20)),
                ('tluszcz', models.CharField(blank=True, default='', max_length=20)),
                ('nasycone', models.CharField(blank=True, default='', max_length=20)),
                ('weglowodany', models.CharField(blank=True, default='', max_length=20)),
                ('cukry', models.CharField(blank=True, default='', max_length=20)),
                ('blonnik', models.CharField(blank=True, default='', max_length=20)),
                ('bialko', models.CharField(blank=True, default='', max_length=20)),
                ('sol', models.CharField(blank=True, default='', max_length=20)),
                ('wyglad_ocena', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('zapach', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('smak', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('konsystencja', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('innowacyjnosc', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('transfer', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Ocena')),
                ('target_lines', models.JSONField(blank=True, default=list)),
                ('external_url', models.URLField(blank=True, default='', help_text='Link SharePoint do oryginalnego zdjęcia (wpisy archiwalne).')),
                ('external_filename', models.CharField(blank=True, default='', help_text='Oryginalna nazwa pliku, do dopasowania zdjęć z SharePoint.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inno_lab/photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('Front opakowania', 'Front opakowania'), ('Tył / etykieta', 'Tył / etykieta'), ('Produkt (środek)', 'Produkt (środek)'), ('Detal / przekrój', 'Detal / przekrój')], default='Front opakowania', max_length=40)),
                ('original_filename', models.CharField(blank=True, default='', max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inno_lab.product')),
            ],
            options={
                'verbose_name': 'Zdjęcie produktu',
                'verbose_name_plural': 'Zdjęcia produktu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('Płatki kukurydziane i wielozbożowe', 'Płatki kukurydziane i wielozbożowe'), ('Granola', 'Granola'), ('Ekstrudaty', 'Ekstrudaty'), ('Poduszki', 'Poduszki'), ('Musli', 'Musli'), ('Owsianki', 'Owsianki'), ('Batony', 'Batony')], max_length=100, verbose_name='Linia docelowa')),
                ('flavour', models.CharField(blank=True, default='', max_length=300, verbose_name='Kierunek do odtworzenia')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start projektu')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Postęp projektu (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='inno_lab.product')),
            ],
            options={
                'verbose_name': 'Action plan',
                'verbose_name_plural': 'Action plany',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('role', models.CharField(choices=[('R&D Manager', 'R&D Manager'), ('Technolog R&D', 'Technolog R&D'), ('Specjalista sensoryki', 'Specjalista sensoryki'), ('Zakupy / Sourcing', 'Zakupy / Sourcing'), ('Produkcja / Linia', 'Produkcja / Linia'), ('Jakość (QA)', 'Jakość (QA)'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=60)),
                ('tasks', models.TextField(blank=True, default='')),
                ('initials', models.CharField(blank=True, default='', help_text='Tylko inicjały — bez pełnych danych osobowych.', max_length=4)),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='inno_lab.transferplan')),
            ],
            options={
                'verbose_name': 'Krok planu',
                'verbose_name_plural': 'Kroki planu',
                'ordering': ['nr'],
            },
        ),
    ]
