# Generated by Django 6.0.5 on 2026-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyStorageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wpis pamięci (narzędzie oryginalne)',
                'verbose_name_plural': 'Wpisy pamięci (narzędzie oryginalne)',
            },
        ),
    ]
